---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_2
---

# **Assignment 2 - Learning about file paths via the command line**

In this assignment, you will use the command-line of your computer to:

+ Use relative file paths that are portable between computers sharing a Git repository
+ Demonstrate the use of "wildcards" to perform actions on groups of files simultaneously
+ Demonstrate redirection of output to files (">" and ">>")
+ Use the pipe "|" to chain output of one program to input of another
+ Use the programs "wc" "ls" "sort" "uniq" "head" "tail" "find" "mkdir" 
+ Create a "for-loop" that combines all of the above skills to run an existing script on many files and summarize the output

**We will cover the commands used here, along with file paths, during class**

___

## First things first, if you haven't done this already...

You need to clone another GitHub repository to your computer. This repository contains all the files (except exams) that we will use for the course. It has several subdirectories, lots of data files, exercises, etc. Most of these can be found on the course website as well, but I want you to have a local copy of everything on your own computer so you can get practice using the command line. 

So, open your terminal and navigate to your Desktop. Then copy/paste the following line to clone our "Data_Course" repository.

```{bash,include=TRUE,eval=FALSE}
git clone https://github.com/gzahn/Data_Course.git
```

This assignment will be completed using the command line in this new "Data_Course" directory.

**All file paths should be relative, starting from the main Data_Course directory**

___

## **For credit...**

1.  Upload a .txt file to Canvas that has the code you wrote to complete each of the following tasks. Your plaintext file should be numbered (1-6) and the code for each task should be on the line(s) below the task number!

2.  You will also be scored on whether new files created as part of this assignment are in their proper place in your
own repository. That means you will need to "stage," "commit," and "push" all changes in your local repository to your GitHub repository.

____________


## Complete the following 6 tasks:

1.  For each of the filenames that begin with "M" in the directory "./Data/data-shell/data/pdb" list the number of lines in each file.


2.  Redirect the output from the previous task to a new file named "m_lines.txt" in

    "../Data_Course_YOURLASTNAME/Assignments/Assignment_2/"
(note that all new files in your personal repository will be checked by the instructor...also, you will need to create that directory)


3.  For the file "animals.txt" in "./Data/data-shell/data/" get an alphabetical list of the unique animal types that were observed and redirect this list to a new file called "unique_animals.txt" in "../Data_Course_YOURLASTNAME/Assignments/Assignment_2/"


4.  In the directory "./Data/" there is a file named "BioLog_Plate_Data.csv"
Write a command that gives a list of the unique carbon substrates the biolog plate measured, and which saves this list as a new file named "unique_C-substrates.txt" in "../Data_Course_YOURLASTNAME/Assignments/Assignment_2/" 


5.  Write a command that finds the longest .txt file (by number of lines) in the directory "../Data/data-shell/data/"
	
	Hint: wc, sort, tail, head


6. In the directory "../Data/data-shell/many_files/" there are a large number of subdirectories. Buried annoyingly inside these subdirectories are some .txt files that all contain a list of numbers (one interger per line). 
There is a shell script in the directory "../Data/data-shell/scripts" called "sum_lines.sh"


  Your task is to run this script on **ALL** the .txt files buried within the "many_files/" directory to output the
  sums of all the lines in each file. This output (on all those files) should be saved in a single file named 
  "file_sums.txt" in "../../../Data_Course_YOUR_LAST_NAME/Assignments/Assignment_2/"
	
This is a tough one. Remember that to run a shell script you need to type "bash PATH_TO_SCRIPT"

Hint: use find -exec and/or a for-loop

## find -exec reminder:
```{bash}
find ../../Data/data-shell/data/animal-counts/ -type f -exec head -1 {} \;
```


## for-loop reminder:
```{bash}
# this will cycle through the files in ../../Data/ with *.txt in the filename
# with each new value, it will echo the filename to the terminal, 
# and then give the first line of the file

for i in ../../Data/*.txt
 do
 echo $i
 head -1 $i
 done
```

On one line, it would look like this:
```{bash, eval=FALSE, include=TRUE}
for i in ../../Data/*.txt;do echo $i;head -1 $i;done
```

