---
title: "Assignment 8"
author: "gzahn"
date: "March 23, 2019"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Assignment 8**

In this assignment, you will use R (within R-Studio) to:
  
+ Load and clean a real data set
+ Conduct exploratory analyses, including informative figures
+ Build and test appropriate models
+ Draw conclusions about your data
+ Combine all of the above into a well-documented R-Markdown report and export (knit) it into an HTML file

**All file paths should be relative, starting from the Assignment_8 directory!! (where you found this file)**

**This means that you need to create a new R-Project named "Assignment_8.Rproj" in your Assignment_8 directory, and work from scripts within that.**


## **For credit...**

1.  Push a completed version of your Rproj and R-markdown file (details at end of this assignment) to GitHub
2.  Your score will also depend on your analyses and presentation of your final report

____________

# Your tasks:

+ Use the data set "../../Data/GradSchool_Admissions.csv"
+ You will explore and model the predictors of graduate school admission
  - the "admit" column is coded as 1=success and 0=failure
  - the other columns are the GRE score, the GPA, and the rank of the undergraduate institution, where I is "top-tier."
+ Document your data explorations, figures, and conclusions in a reproducible R-markdown report

