## Assignment 1

________________
#### First, read the following document. It will set the stage for version control and why we will be using it.

https://github.com/gzahn/Data_Course/blob/master/readings/Bryan_2017_Excuse_me%2C_do_you_have_a_moment_to_talk_about_vers.pdf

________________

1.  If you do not have R installed on your computer, install it. Google "how to install R" for instructions.
2.  Install RStudio on your computer. [https://www.rstudio.com/products/rstudio/download/#download]
3.  Download and install git and create an account on github.com. Choose a professional-sounding username!
4.  Create a new repository on your GitHub page called "Data_Course_YOUR-LAST-NAME"
  + Look for the "+" in the top menu
  + Enter the name "Data_Course_Assignments" where prompted
  + Leave the "Public" option checked
  + Be sure to check the box " Initialize this repository with a README"
5.  Make a directory on your computer for this course. Directory "paths" look different on Windows vs Mac/Linux. On a linux machine, this will look something like: "~/Desktop/Data_Course_YOUR-LAST-NAME/"
  + Create a subdirectory called "Assignments" within that Data_Course directory
7.  Now create an entirely new directory called "Data_Course_materials" - This will contain all the stuff your instructor makes (assignments, readings, example code, etc.) 
6.  Open your terminal and navigate to the "Data_Course_materials" directory you just created. (the command "cd ~/Desktop/Data_Course_materials" would navigate there, if that was your "path")
7.  Clone the course materials into this directory by typing: git clone "https://github.com/gzahn/Data_Course"
8.  Go back to your "Data_Course_YOUR-LAST-NAME/assignments" directory and clone your new GitHub repository (that you created online)
  + Hint: use the same command as above, but modify the web address to your new GitHub repository
9.  Back in your terminal, make sure you are still in the "assignments" directory (you should now see a file called "README.md" in there), and type the following commands (exactly), in order:
  + echo "This README file contains information about my uploaded assignments" >> README.md
  + git add README.md
  + git commit -m "1st commit"
  + git push
  + (Here it will ask for your GitHub userID and password....enter those when asked)
10. Check back on your GitHub page online...if you see that new text ("This README file contains information about my uploaded assignments") then you are finished!
11. To get credit, upload a link to your GitHub repository to "Assignment 1" in Canvas. I'll click on that and see whether your README.md file is correct.

#### We will discuss what is actually going on with all of this in class, but this is to test whether you can follow precise instructions and troubleshoot.

#### **Don't be afraid to ask others/instructor/Google for help with this!**