library(dplyr)
library(tidyr)
library(ggplot2)
library(broom)
library(fitdistrplus)
library(MASS)
library(lme4)
library(modelr)

getwd()
setwd("~/Desktop/GIT_REPOSITORIES/Data_Course/data/")
df = read.csv("mushroom_growth.csv")

plot(fitdist(df$log10_GrowthRate, distr = "norm"))
plot(fitdist(df$GrowthRate, distr = "lnorm"))
plot(fitdist(df$GrowthRate, distr = "logis"))
plot(fitdist(df$GrowthRate, distr = "gamma"))

plot(fitdist(log10(df$GrowthRate), distr = "norm")) 

df$log10_GrowthRate = log10(df$GrowthRate)



summary(df)

mod1 = aov(GrowthRate ~ (Humidity+Nitrogen+Light)*Species, data = df)
mod2 = aov(GrowthRate ~ (Humidity*Nitrogen*Light)*Species, data = df)
mod3 = aov(GrowthRate ~ (Humidity*Light)*Species, data = df)
mod4 = aov(GrowthRate ~ Humidity+Nitrogen+Light+Species+Humidity:Species, data = df)




summary(mod1)
summary(mod2)
summary(mod4)


plot(TukeyHSD(mod1))
TukeyHSD(mod2)

anova(mod1, mod2)

library(modelr)
df=add_predictions(df,mod1, var="mod1")
df=add_predictions(df,mod2, var="mod2")
df=add_predictions(df,mod3, var="mod3")
df=add_predictions(df,mod4, var="mod4")


sqrt(mean((df$mod1 - df$GrowthRate)^2))
sqrt(mean((df$mod2 - df$GrowthRate)^2))
sqrt(mean((df$mod3 - df$GrowthRate)^2))
sqrt(mean((df$mod4 - df$GrowthRate)^2))


# exploratory plots
plot1 = ggplot(mod1, mapping = aes(x=Light, y=GrowthRate, col = Species))
plot1 + geom_point() + geom_smooth()

plot2 = ggplot(df, mapping = aes(x=Humidity, y=GrowthRate, col = Species))
plot2 + geom_boxplot()

plot3 = ggplot(df, mapping = aes(x=Light, y=GrowthRate, col = Humidity)) 
plot3 + geom_point() + geom_smooth()

plot4 = ggplot(mod2, mapping = aes(x=Light, y=GrowthRate, col = Species))

#Species:Light, Species:Nitrogen, Species:Temperature, Species:Humidity, Light:Humidity, Temperature:Humidity, Species:Light:Humidity

ggplot(df, mapping = aes(x= Temperature, y= GrowthRate, col = Species)) +
  geom_point() + geom_smooth(method = "aov") + 
  ggtitle("Growth as a function of Temperature") + 
  labs(subtitle = "Color by Species")

boxplot(df$GrowthRate ~ df$Species*df$Humidity)

#predictive models
model_1 = df %>% add_predictions(model = mod1) 
mod_aov = aov(GrowthRate ~ (Humidity+Nitrogen+Light+Species)*pred, data = model_1)

model_df2 = df %>% add_predictions(model = mod2)
mod_aov2 = aov(GrowthRate ~ (Humidity*Nitrogen*Light*Species)*pred, data = model_df2)



summary(mod_aov) 
summary(mod_aov2) 

TukeyHSD(mod_aov)
anova(mod_aov,mod_aov2) #tells me that pred model mod_aov2 is sig dif from pred model mod_aov

for(h in names(model_1)){
  plot(model_1[,"GrowthRate"] ~ model_1[,h], xlab = h, ylab = "GrowthRate", main = h)}

ggplot(data = model_1) +
  geom_point(aes(x=Light, y=GrowthRate, col = Species)) +
  geom_smooth(aes(x=Light, y=GrowthRate, col = Species)) +
  geom_point(aes(y=pred, x=Light)) +
  geom_smooth(aes(y=pred, x=Light, color = Species),linetype = 5)




?linetype

summary(mod1)
+
  geom_smooth(aes(x=Nitrogen, y=GrowthRate),col = "Black") +
  geom_smooth(aes(pred,GrowthRate,col = Species))

# ggplot(data = model_1) +
#   geom_point(aes(x=Light, y=GrowthRate, col = Species)) +
#   # geom_point(aes(x=pred, y=GrowthRate, col=Species)) +
#   geom_smooth(aes(x=pred, y=GrowthRate),col = "Black")

# ggplot(data = model_df2) +
#   geom_point(aes(x=Light, y=GrowthRate, col = Species)) +
#   geom_point(aes(x=pred, y=GrowthRate, col=Species)) +
#   geom_smooth(aes(x=pred, y=GrowthRate),col = "Black")

ggplot(model_df2) + 
  geom_point(aes(x=pred, y=GrowthRate, col=Species), alpha = 0.5) +
  geom_smooth(aes(x=pred, y=GrowthRate),col = "Black", method = "lm")

?geom_smooth

?read.csv
```{r echo=TRUE}
ggplot(df) +
  geom_point(aes(x=mod1,y=GrowthRate), col = "Red") +
  geom_smooth(aes(x=mod1,y=GrowthRate), col = "Red") +
  geom_point(aes(x=mod2,y=GrowthRate), col = "Blue") +
  geom_smooth(aes(x=mod2,y=GrowthRate), col = "Blue")

```

