Exercise 1

Consider a vector:
  
  x <- c(4,6,5,7,10,9,4,15)

What is the value of:
  
  c(4,6,5,7,10,9,4,15) < 7

a. TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE

b. TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE

c. FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE

d. TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE

e. TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE



Exercise 2

Consider two vectors:
  
  p <- c (3, 5, 6, 8)

and

q <- c (3, 3, 3)

What is the value of:
  
  p+q

a. 6, 8, 6, 8

b. 6, 8, 0, 0

c. 6, 8, NA, NA

d. 3, 5, 6, 8 Warning message: In p+q : longer object length is not a multiple of shorter object length

e. 6, 8, 9, 11



Exercise 3

If:
  
  Age <- c(22, 25, 18, 20)
Name <- c("James", "Mathew", "Olivia", "Stella")
Gender <- c("M", "M", "F", "F")

then what is the R-code for getting the following output;

##   Age   Name Gender
## 1  22  James      M
## 2  25 Mathew      M

a.

DataFrame = data.frame(c(Age), c(Name), c(Gender))
subset(DataFrame, Gender == "M")

b.

DataFrame = data.frame(c(Age),c(Name),c(Gender))
subset(Gender=="M"), eval=FALSE 

c.

DataFrame = data.frame(Age,Name,Gender)
subset(DataFrame,Gender=="M")

d.

DataFrame = data.frame(c(Age,Name,Gender))
subset(DataFrame,Gender=="M")



Exercise 4

If

z <- 0:9

then what is the output from the following R-statements:
  
  digits <- as.character(z)
as.integer(digits)

a. Error in subset. object 'z' not found

b. 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

c. "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"

d. "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"

e. 0, 0, 0, 0, 0, 0, 0, 0, 0
Learn more about vectors in the online course R Programming A-Z™: R For Data Science With Real Exercises! This course had more than 68,000 students enrolled already and does not require prior knowledge of R.

Exercise 5

Consider the vector:
  
  x <- c(1,2,3,4)

What is the value of k for:
  
  (x+2)[(!is.na(x)) & x > 0] -> k

a. 1, 2, 3, 4

b. 1, 4, 9, 16

c. Error: object 'k' not found

d. 3, 4, 5, 6

e. numeric(0)



Exercise 6

Consider the AirPassenger data set

data(AirPassengers)

Which statement will produce the following output?

##  [1] 112 118 132 129 121 135 148 148 136 119 104 118

a. AirPassengers[time(AirPassengers) >= 1949 & time(AirPassengers) < 1950, 12]

b. AirPassengers[AirPassengers >= 1949 & AirPassengers < 1950]

c. AirPassengers[time(AirPassengers) >= 1949 & time(AirPassengers) < 1950]

d. AirPassengers[AirPassengers >= 1949 & AirPassengers < 1950, 12]

e. c[[1]]



Exercise 7

If

x <- c(2, 4, 6, 8)

and

y <- c(TRUE, TRUE, FALSE, TRUE)

What is the value of:
  
  sum(x[y])

a. 20

b. 8

c. 14

d. NA



Exercise 8

Consider the vector:
  
  x <- c(34, 56, 55, 87, NA, 4, 77, NA, 21, NA, 39)

Which R-statement will count the number of NA values in x?

a. count(is.na(X))

b. length(is.na(x))

c. sum(is.na(x))

d. count(!is.na(x))

e. sum(!is.na(x))