---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_7
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Assignment 7**

In this assignment, you will use R (within R-Studio) to:

+ Take a real life data set and wrangle it into shape
+ Use a data dictionary to clean and merge two related data sets

**All file paths should be relative, starting from *your* Assignment_7 directory!!**

**This means that you need to create a new R-Project named "Assignment_7.Rproj" in your Assignment_7 directory, and work from scripts within that.**


## **For credit...**

1.  Push a completed version of your Rproj and R-script (details at end of this assignment) to GitHub
2.  Your score will also depend on whether any files generated in this workflow are found in your repository


____________

# Your tasks:

  + Import the 4 related datasets found in the Data_Course/Data/flights/ directory. There should be: 
    - airlines.csv
    - airports.csv
    - jan_flights.csv
    - Jan_snowfall.csv
  + Combine the data sets appropriately to investigate whether departure delay was correlated with snowfall amount
  + You will need to think carefully about column names
  + Plot average departure delays by state over time
  + Plot average departure delays by airline over time
  + Plot effect of snowfall on departure *and* arrival delays
_____________


